const express = require("express");
const controller = require("../controllers/user.controller");
const paymentController = require("../controllers/payment.controller");
const { requireAuth, requireAdmin } = require("../middlewares/auth.middleware");
const router = express.Router();
router.post("/login", controller.login);
router.post("/", controller.createUser);
router.get("/", requireAuth, requireAdmin, controller.getUsers);
router.get("/me", requireAuth, controller.me);
router.patch("/me", requireAuth, controller.updateProfile);
router.post("/me/addresses", requireAuth, controller.addAddress);
router.delete("/me/addresses/:addressId", requireAuth, controller.deleteAddress);
router.put("/me/addresses/:addressId/default", requireAuth, controller.setDefaultAddress);
router.post("/check-in", requireAuth, controller.checkIn);
router.post("/draw", requireAuth, controller.draw);
router.post("/top-up", requireAuth, paymentController.createTopUp);
router.get("/top-up", requireAuth, paymentController.getCurrentTopUp);
router.get("/top-up/:id", requireAuth, paymentController.getTopUpStatus);
module.exports = router;
